hipagesgroup/data-tools

- setup.cfg
---
* https://github.com/hipagesgroup/data-tools/issues/5
---
* unquote the url as that is likely causing issues while uploading
---
* NA
> fix: unquote the url in setup.cfg

- .circleci/config.yml
- setup.cfg
- setup.py
---
* #5 
---
* Install pbr in circle ci
* Add long description
* Add licence file with the wheel
---
* NA
> feat: Add long description and fix pbr

- setup.py
---
* #5 
---
* Add long description from the readme
---
* NA
> chore: Read long description using readme file

- .circleci/config.yml
- hip_data_tools/authenticate.py
- hip_data_tools/aws/athena.py
- hip_data_tools/aws/s3.py
- setup.py
- tests/aws/test_s3.py
---
* Added basic s3 utility methods
* Modified AwsConnection to contain both get_resource and get_client methods
* paused code coverage merging / unittests
---
* Added Unittests
> feat: Add S3 utility

- hip_data_tools/aws/s3.py
- tests/aws/test_s3.py
---
* https://github.com/hipagesgroup/data-tools/issues/11
---
* fixed the positional arguments that were swapped
* Added serialise and upload methods
---
* unit tests with mock
> fix: s3 serialise methods

- hip_data_tools/aws/s3.py
- tests/aws/test_s3.py
---
* https://github.com/hipagesgroup/data-tools/issues/16
---
* Added s3 function to copy files recursively between buckets
* Added s3 functions to read and delete files in a bucket
---
* Unit tests with mocked s3
> feat: Add a s3 function to copy files recursively between buckets

- hip_data_tools/apache/kafka.py
- hip_data_tools/common.py
- setup.py
- tests/apache/test_kafka.py
---
https://github.com/hipagesgroup/data-tools/issues/18
---
Adding wrappers to the kafka functionality of confluent kafka
---
Unit tests provided
> feat: adding kafka

- setup.py
---
Build failing due to pytest issues
---
pinning the version of attrs library 
---
builds now passing
> fix: fixing error with the latest pytest

- hip_data_tools/hipages/version_tracking.py
- tests/hipages/test_version_tracking.py
---
https://github.com/hipagesgroup/data-tools/issues/20
---
Adding a class which enables tracking of code to produce a single dictionary. 
---
Unit tests provided
> feat: adding version tracker

- hip_data_tools/hipages/version_tracking.py
- tests/hipages/test_version_tracking.py
---
https://github.com/hipagesgroup/data-tools/issues/24#issue-507566886
---
Fixing problem with nested lists being returned when getting decorators from a file
---
unit tests provided. 
Code ran locally and produces versioning json
> Fix version control

- hip_data_tools/hipages/version_tracking.py
---
small doco change
---
N/A
---
N/A
> fix: adding documentation

- hip_data_tools/aws/s3.py
---
* NA
---
* Update to a docstring
---
* Not required, as no code only doco was changed.
> chore: Update the doco to spell out ability to use standard boto objects

- hip_data_tools/aws/s3.py
- hip_data_tools/hipages/version_tracking.py
---
Bug causing athena services to fail
---
fixed typo
---
unit test
> Fix: typo of athema

- README.md
---
* Last merge did not have a semantic title and thus build failed. this will fix it.
> chore: Empty commit to engage semantic bot

- setup.py
---
PyArrow was included in the tests, but not in the install. This means that unit tests will pass but the code doesn't work once deployed. 
Now fixed
---
N/A
> fix: adding pyarrow to install

- hip_data_tools/aws/athena.py
- hip_data_tools/aws/common.py
- hip_data_tools/aws/s3.py
- tests/aws/test_athena.py
- tests/aws/test_s3.py
---
* NA
---
* Add feature in AthenaUtil to retrive table's location on s3
* Add feature in S3Util to list all files under a given location
---
* Unittests
> feat: Add helper methods in S3 and Athena to get table and files

- hip_data_tools/apache/cassandra.py
- hip_data_tools/etl/s3_to_cassandra.py
- setup.py
- tests/apache/test_cassandra.py
---
* NA 
---
* Added a utility to combine S3 util and Cassandra util, and provide an ETL Utility to upsert Parquet files stored in S3 to Cassandra
---
* Unittests
Integration test using code:
```
import logging as log
from datetime import datetime
from unittest import TestCase
from cassandra.cluster import DCAwareRoundRobinPolicy
from hip_data_tools.apache.cassandra import CassandraConnectionSettings, CassandraSecretsManager
from hip_data_tools.aws.common import AwsConnectionSettings
from hip_data_tools.common import DictKeyValueSource
from hip_data_tools.etl.s3_to_cassandra import S3ToCassandraSettings, S3ToCassandra
import logging
logging.basicConfig()
logging.getLogger().setLevel(logging.INFO)
def test__integration(self):
settings = S3ToCassandraSettings( …
```
> feat: [DP-285] Add utility to transfer data from s3 to cassandra

- hip_data_tools/etl/s3_to_cassandra.py
---
* Made a method public
---
* unittests
> feat: Make individual file creation public

- hip_data_tools/apache/cassandra.py
---
* Remove progress bar from Cassandra batched data frame operation
---
* unit tests
> fix: Remove progress bar as it interferes with logging

- hip_data_tools/apache/cassandra.py
- hip_data_tools/etl/athena_to_cassandra.py
- hip_data_tools/etl/s3_to_cassandra.py
- setup.py
- tests/apache/test_cassandra.py
---
* Add the ability to upsert to Cassandra using both batched statement or a simple prepared statement
---
* Unit tests
* Integration Test
```
import logging as log
from datetime import datetime
from unittest import TestCase
from cassandra.cluster import DCAwareRoundRobinPolicy
from hip_data_tools.apache.cassandra import CassandraConnectionSettings, CassandraSecretsManager
from hip_data_tools.aws.common import AwsConnectionSettings
from hip_data_tools.common import DictKeyValueSource
from hip_data_tools.etl.athena_to_cassandra import AthenaToCassandraSettings, AthenaToCassandra
import logging
logging.basicConfig()
logging.getLogger().setLevel(logging.INFO)
def test__integration():
settings = AthenaToCassandraSettings(
source_database="dev",
source_table="xxx", …
```
> feat: [DP-282] individual row insert for cassandra

- README.md
---
* https://hipagesgroup.atlassian.net/browse/DP-254
---
* Changed the __init__.py file to configure google package as a module
---
* Unit tests
> feat: [DP-254] Added google module

- hip_data_tools/etl/google_sheet_to_athena.py
- hip_data_tools/google/common.py
- hip_data_tools/google/sheets/common.py
- tests/etl/google_sheet_to_athena.py
- tests/google/test_sheets.py
---
---
* Changed the code and tests to use google api key dictionary object instead of a file
---
* Unit tests
> feat: [DP-254] ModifIed the code to use  google api key object instead of file location

- hip_data_tools/aws/common.py
---
---
* Fixed a comment to update the version number
---
* Unit tests
> feat: fixed a doc comment

- hip_data_tools/aws/s3.py
- tests/aws/test_s3.py
---
---
* Added a function to copy files between s3 buckets
---
* Unit tests
> feat: Added s3 function to copy files between buckets

- hip_data_tools/aws/s3.py
- tests/aws/test_s3.py
---
* Changed the upload_dataframe_as_parquet logic
---
*  Unit tests
> feat: Changed the upload_dataframe_as_parquet logic

- README.md
- hip_data_tools/aws/common.py
- hip_data_tools/etl/athena_to_adwords.py
- hip_data_tools/etl/athena_to_dataframe.py
- hip_data_tools/etl/common.py
- hip_data_tools/etl/s3_to_cassandra.py
- hip_data_tools/etl/s3_to_dataframe.py
- hip_data_tools/google/adwords.py
- tests/etl/athena_to_adwords.py
- tests/etl/athena_to_dataframe.py
- tests/etl/test_common.py
- tests/etl/test_s3_to_dataframe.py
---
* Add ETL module to load data from Athena to Adwords
---
* See all the integration tests
> feat: [DP-357] End to End offline adwords conversion from Athena

- hip_data_tools/etl/athena_to_adwords.py
- hip_data_tools/etl/athena_to_cassandra.py
- hip_data_tools/etl/athena_to_dataframe.py
- hip_data_tools/etl/google_sheet_to_athena.py
- hip_data_tools/etl/google_sheet_to_s3.py
- hip_data_tools/etl/s3_to_cassandra.py
- hip_data_tools/etl/s3_to_dataframe.py
- tests/etl/athena_to_adwords.py
---
* Fixed the internal private vars to dunderscore so they donot interfere with parent class vars
---
*  Unit tests
> feat: [DP-357] Fix the internal variables and isolate from super calsses

- hip_data_tools/etl/athena_to_athena.py
- hip_data_tools/etl/athena_to_s3.py
- hip_data_tools/etl/common.py
- tests/etl/athena_to_athena.py
---
* https://github.com/hipagesgroup/data-tools/issues/53
---
* Adds two ETLs to transfer data from 
-- Athena sql to Athena table
-- Athena sql to S3
---
* Unit tests
> feat: Add ETL for Athena to Athena and S3

- .circleci/config.yml
- hip_data_tools/common.py
- hip_data_tools/etl/adwords_to_s3.py
- hip_data_tools/etl/s3_to_s3.py
- hip_data_tools/google/adwords.py
- setup.py
- tests/etl/adwords_to_s3.py
- tests/google/adwords.py
- tests/test_common.py
---
* Adwords to S3 data transfer etl calsses defined
---
* Integration tests
> feat: Add Adwords to S3 parquet ETL tool

- hip_data_tools/aws/athena.py
- hip_data_tools/etl/adwords_to_athena.py
- hip_data_tools/etl/adwords_to_s3.py
- hip_data_tools/etl/google_sheet_to_athena.py
- hip_data_tools/google/adwords.py
- tests/aws/test_athena.py
- tests/etl/adwords_to_athena.py
---
* New etl class to transfer data from adwords and create athena table on top
---
* Integration Tests
> feat: [DP-372] Added ETL tool for Adwords objects to Athena

- hip_data_tools/etl/adwords_to_s3.py
- hip_data_tools/google/adwords.py
- tests/etl/adwords_to_athena.py
---
* Add the ability to configure wether to download data with zero impression in an adwords report
* Pass through keyword arguments to the download report method in adwords library
---
* Existing Unit tests pass
> feat: [DP-385] Add ability to control zero impressions flag

- hip_data_tools/etl/adwords_to_s3.py
---
* Hot fix for adword StopIteration issue
---
* Unit tests
> fix: Fixed adwords StopIteration issue

- hip_data_tools/aws/s3.py
- hip_data_tools/google/adwords.py
---
* Added few debug logs for adword debugging purposes
---
* Unit tests
> fix: Added adword debug logs

- hip_data_tools/etl/adwords_to_s3.py
---
* Break page iteration when an empty response is received
---
* Unit tests
> fix: Handled adword api empty response

- hip_data_tools/apache/cassandra.py
- hip_data_tools/apache/kafka.py
- hip_data_tools/aws/athena.py
- hip_data_tools/aws/s3.py
- hip_data_tools/etl/athena_to_adwords.py
- hip_data_tools/etl/s3_to_cassandra.py
- hip_data_tools/etl/s3_to_dataframe.py
- hip_data_tools/google/adwords.py
- hip_data_tools/google/sheets.py
---
* this is precursor general refactor as a precursor to other work
---
* Existing unit tests
> chore: general upgrades

- hip_data_tools/aws/athena.py
---
* Added functions to generate ctas queries with partitions
---
* Unit tests
> fix: Added ctas query generation

- hip_data_tools/aws/athena.py
---
* Added json storage format lookup
---
* Unit tests
> fix: Added json based Athena table creation support

- hip_data_tools/etl/athena_to_athena.py
---
* add a uuid location on the output bucket for athena results
---
* Unittests
> fix: Add athena result destination

- hip_data_tools/aws/athena.py
- tests/aws/test_athena.py
---
* Ability to get column metadata for an athena table
---
* Unittests
> feat: Extract column metadata from glue

- hip_data_tools/aws/athena.py
---
* Add boolean datatypes map
---
* Unittests
> feat: Add boolean datatype for athena

- hip_data_tools/aws/athena.py
- tests/aws/test_athena.py
---
* Used String as the default athena column type
---
* Unit tests
> fix: Added default athena column type

- .github/semantic.yml
- docs/Makefile
- docs/make.bat
- docs/source/conf.py
- docs/source/hip_data_tools.apache.rst
- docs/source/hip_data_tools.aws.rst
- docs/source/hip_data_tools.etl.rst
- docs/source/hip_data_tools.google.rst
- docs/source/hip_data_tools.hipages.rst
- docs/source/hip_data_tools.rst
- docs/source/index.rst
- docs/source/modules.rst
- hip_data_tools/apache/kafka.py
- hip_data_tools/common.py
- setup.py
---
* https://github.com/hipagesgroup/data-tools/issues/89
---
* Initialise sphinx doco
---
* should show up here https://hip-data-tools.readthedocs.io/en/doco-sphinx/
> feat: Automated documentation using sphinx

- hip_data_tools/etl/adwords_to_s3.py
- tests/etl/adwords_to_s3.py
---
* Added the ability to add custom file name prefix to files which are loaded from adwords api
---
* Unit Tests
> fix: Added target_file_prefix to AdWordsToS3Settings

- README.md
- hip_data_tools/aws/athena.py
- hip_data_tools/aws/common.py
- hip_data_tools/etl/adwords_to_athena.py
- hip_data_tools/etl/athena_to_athena.py
- hip_data_tools/etl/athena_to_cassandra.py
- hip_data_tools/etl/athena_to_dataframe.py
- hip_data_tools/etl/athena_to_s3.py
- hip_data_tools/etl/google_sheet_to_athena.py
- tests/aws/test_athena.py
- tests/aws/test_athena_partitions_handler.py
- tests/etl/adwords_to_athena.py
---
* Added utility to add athena partitions as chunks
---
* Unit tests
> feat: Added athena table partitions handler utility

- hip_data_tools/aws/athena.py
---
* Added Athena work groups support
---
* N/A
> feat: Added Athena custom workgroups support

- hip_data_tools/common.py
- tests/etl/adwords_to_s3.py
---
* Avoid getting None values for common integer fields
---
* Unit tests
> fix: Handled None values for common integer fields

- hip_data_tools/common.py
- tests/test_common.py
---
* Handling list type in the dataframe
---
* Unit tests
> feat: Add complex data type handling support for data tools adwords utility

- hip_data_tools/common.py
- hip_data_tools/etl/adwords_to_s3.py
- tests/test_common.py
---
* Added a function to handle invalid values for common integer fields
---
* Unit tests
> fix: Validate and fix common integer fields

- hip_data_tools/common.py
- tests/test_common.py
---
* Handled list of objects in the adwords response
---
* Unit tests
> fix: [DP-468] Adwords response with list of objects

- hip_data_tools/apache/kafka.py
---
* Fixed kafka logging wrong reference variable
---
* N/A
> fix: kafka logging issue

- hip_data_tools/apache/kafka.py
- setup.py
- tests/apache/test_kafka.py
- tests/etl/test_s3_to_dataframe.py
---
* Fixed the kafka module to use updated upload_dataframe_as_parquet s3 function
---
* N/A
> fix: s3 utility usage in kafka module

- .codeclimate.yml
- example/etl/s3_to_s3_file_tansfer.py
- hip_data_tools/etl/common.py
- hip_data_tools/etl/s3.py
- hip_data_tools/etl/s3_to_s3.py
- tests/etl/test_s3_to_dataframe.py
- tests/etl/test_s3_to_s3.py
---
* https://github.com/hipagesgroup/data-tools/issues/119
* https://github.com/hipagesgroup/data-tools/issues/120
---
* Added some abstract base classes to serve as the foundation of a more modular and extensible ETL framework
* Refactored S3ToS3 etl to use the new framework
* Added example
---
* Unit tests
> feat: Refactor to make ETL classes more modularised

- README.md
---
* Not required for documentation change
---
* Not required for documentation change
---
* Not required for documentation change
> chore: Add new badges from code climate

- hip_data_tools/google/adwords.py
- setup.py
- tests/google/adwords.py
- tests/google/test_adword_functions.py
---
* Modified get_parallel_payloads method to handle edge cases 
---
* Unit tests
> feat: Modified get_parallel_payloads method to handle edge cases 

- hip_data_tools/etl/athena_to_dataframe.py
- hip_data_tools/etl/s3_to_dataframe.py
- setup.py
---
* na
---
* Updated misleading documentation
---
* na
> fix: updated documentation

- .github/CODEOWNERS
---
* NA
---
* Update code owners to the data platform team
---
* NA
> fix: Update code owners

- hip_data_tools/etl/adwords_to_s3.py
- tests/etl/adwords_to_athena.py
---
* Fix adwords to s3 integer field masking
---
* Integration test
> fix: adwords to s3 int fields masking

- hip_data_tools/aws/s3.py
- tests/aws/test_s3.py
---
* 
---
* enable passing arguments to the pandas _to_parquet function
---
* unit tests
> feat: pass parameters to parquet writer

- hip_data_tools/etl/adwords_to_s3.py
- hip_data_tools/oracle/mysql.py
- setup.py
- tests/aws/test_s3.py
- tests/etl/adwords_to_athena.py
- tests/etl/adwords_to_s3.py
- tests/etl/athena_to_adwords.py
- tests/etl/athena_to_dataframe.py
- tests/etl/google_sheet_to_athena.py
- tests/etl/s3_to_cassandra.py
- tests/etl/test_adwords_reports_to_s3.py
- tests/etl/test_s3_to_dataframe.py
- tests/etl/test_s3_to_s3.py
- tests/oracle/test_mysql.py
---
* Added a Mysql utility to read and write to mysql
---
*
> feat: Add mysql utility

- hip_data_tools/etl/athena_to_adwords.py
- hip_data_tools/etl/common.py
---
https://github.com/hipagesgroup/data-tools/issues/136
---
Adding logging statements to the athena -> adwords modules to help with debugging.
---
Unit tests
> feat: adding debug logging commands

- setup.py
---
* https://github.com/hipagesgroup/data-tools/issues/138
---
* fix boto3 dependency to 1.17.32
---
*
> fix: tie down boto3 dependency

- hip_data_tools/etl/athena_to_adwords.py
- hip_data_tools/etl/common.py
---
The athena->adwords utility previously only returned verification issues. Now it returns all successful api results alongside verification failures and failure responses from the Google adwords api
---
unit tests
> fix: Adwords athena return failures
